services:
  project.repository.api:
    class: Transporte\UserBundle\Repository\ApiUserRepository
    arguments:
      - "@logger"
      - "@curl.service"
      - "@security.token_storage"

  project.token.user_provider:
    class: Transporte\UserBundle\Security\TokenUserProvider
    arguments:
      - "@logger"

  project.token.authenticator:
    class: Transporte\UserBundle\Security\TokenAuthenticator
    arguments:
      - "@logger"
      - "@project.repository.api"