imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    web_path: %kernel.root_dir%/../web
    locale: es
    app_title: Transporte
    app_description: Transporte
    files_directory: '%kernel.root_dir%/../web/uploads'
    from_email: noreply@transporte.com

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        web_path: %web_path%
        locale: "%locale%"
        app_title: "%app_title%"
        app_description: "%app_description%"
        files_directory: "%files_directory%"
        http_web: "%http_web%"
        link_web: "%link_web%"
        url_web: "%http_web%://%link_web%"
        api_google_key: "%api_google_key%"

services:
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    CoreBundle:  ~
                    UserBundle:  ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Transporte\UserBundle\Entity\User
    profile:
        form:
            type: Transporte\UserBundle\Form\ProfileFormType
    from_email:
        address:        "%from_email%"
        sender_name:    "%app_title%"
    group:
        group_class: Transporte\UserBundle\Entity\Group
    registration:
        confirmation:
            template:   FOSUserBundle:Registration:email.txt.twig
            from_email:
                address:        "%from_email%"
                sender_name:    "%app_title%"
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        form:
            type: Transporte\UserBundle\Form\Type\ResettingFormType
    service:
        user_manager: pugx_user_manager

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false

# FOSRest Configuration
fos_rest:
    body_listener: true
    format_listener:
        rules:
            # setting fallback_format to false means that instead of considering the next rule in case of a priority mismatch, a 406 will be caused
            - { path: '^/image', priorities: ['jpeg', 'gif'], fallback_format: false, prefer_extension: true }
            # setting fallback_format to null, while setting exception_fallback_format to xml, will mean that in case of an exception, xml will be used
            - { path: '^/api', priorities: [ 'json'], fallback_format: json, prefer_extension: true }
            # setting a priority to */* basically means any format will be matched
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/../src/Transporte/UserBundle/Resources/config/serializer"

liip_imagine:
    filter_sets:
        my_filter:
            format: jpeg
            filters:
                strip: ~
                thumbnail: { size: [500, 400], mode: inset }
                watermark:

                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../src/Transporte/CoreBundle/Resources/public/images/watermark.png

                    # size of the water mark relative to the input image
                    size: 0.25

                    # set the position of the watermark
                    position: bottomright