user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@CoreBundle/Controller/"
    type:     annotation

api_user:
  resource: '@UserBundle/Resources/config/routing.yml'

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"