security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        token:
            id: project.token.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: true
        main:
            pattern: ^/
            provider: token
            anonymous: true
            simple_form:
                authenticator: project.token.authenticator
                check_path: login_check
                login_path: login
                use_referer: true
                failure_path: login
            logout:
                path: /logout
                target: login
            remember_me:
                secret:   '%secret%'
                lifetime: 86400
                path:     /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: ROLE_USER }