# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.file.twig.extension:
    class: Transporte\CoreBundle\Twig\Extension\FileExtension
    tags:
      - { name: twig.extension }
  app.class.twig.extension:
    class: Transporte\CoreBundle\Twig\Extension\ClassTwigExtension
    tags:
      - { name: twig.extension }
  menu.factory:
    class: Transporte\CoreBundle\Factory\MenuFactory
    arguments: ['@security.authorization_checker']
  datatable.serverside.service:
    class: Transporte\CoreBundle\Service\DataTableServerSideService
    arguments: ["@doctrine.orm.entity_manager"]
  flashbag_service:
    class: Transporte\CoreBundle\Service\FlashBagService
    arguments: ['@session']
  email_service:
    class: Transporte\CoreBundle\Service\EmailService
    arguments: ['@mailer']
  encrypt_service:
    class: Transporte\CoreBundle\Service\EncryptService
  validator_service:
    class: Transporte\CoreBundle\Service\ValidatorService
    arguments: ['@validator']
  file_service:
    class: Transporte\CoreBundle\Service\FileService
  file_uploader:
    class: Transporte\CoreBundle\Service\FileUploader
    arguments: ['%files_directory%', '@liip_imagine.data.manager', '@liip_imagine.filter.manager']
  document_listener:
      class: Transporte\CoreBundle\EventListener\DocumentUploadListener
      arguments: ['@file_uploader', '@security.token_storage', '@flashbag_service', "@doctrine.orm.entity_manager"]
      tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postPersist }
          - { name: doctrine.event_listener, event: preUpdate }
  configuration_service:
    class: Transporte\CoreBundle\Service\ConfigurationService
    arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
